# name: "c153_topfix_ne240pg3_FMTHIST_QxQsst_xic_x02"
# name: "c153_topfix_ne240pg3_FMTHIST_L56_86km_xic_x02"
A:
  name: "c153_topfix_ne240pg3_FMTHIST_L56_86km_xic_x02" 
  user: "juliob"
  subdir: "hist"
  SrcGrid: "ne240pg3"
  Hkey: "c"
  DstGrid: "latlonOxO"
  hsPat: "cam.h1i"
  ymdPat: [ "2004-06-*" , "2004-07-*", "2004-08-*",]
  parameters:
    param1: 1
    param2: 2
########################
#
########################
ne240x2:
  name: "c153_topfix_ne240pg3_FMTHIST_xic_x02"
  user: "juliob"
  subdir: "hist"
  SrcGrid: "ne240pg3"
  Hkey: "c"
  DstGrid: "latlonOxO"
  hsPat: "cam.h1i"
  ymdPat: "2004-07-*"
  parameters:
    param1: 1
    param2: 2
ne240x2_QxQsst:
  name: "c153_topfix_ne240pg3_FMTHIST_QxQsst_xic_x02"
  user: "juliob"
  subdir: "hist"
  SrcGrid: "ne240pg3"
  Hkey: "c"
  DstGrid: "latlonOxO"
  hsPat: "cam.h1i"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2

