plot:
    field: 'N/A'
    season: 'jja'
validation:
    data: 'ERA5'
    years: '*'
A:
  name: "c64_gwR2_ne30pg3_FMTHIST_topfix_oldCTL_qbotune_x03"
  user: "juliob"
  subdir: "hist"
  SrcGrid: "ne30pg3"
  Hkey: "c"
  DstGrid: "fv1x1"
  hsPat: "cam.h0a"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
ne240x2:
  name: "c153_topfix_ne240pg3_FMTHIST_xic_x02"
  user: "juliob"
  subdir: "hist"
  SrcGrid: "ne240pg3"
  Hkey: "c"
  DstGrid: "latlonOxO"
  hsPat: "cam.h1i"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
ne240x2_L56:
  name: "c153_topfix_ne240pg3_FMTHIST_L56_86km_xic_x02"
  user: "juliob"
  subdir: "hist"
  SrcGrid: "ne240pg3"
  Hkey: "c"
  DstGrid: "latlonOxO"
  hsPat: "cam.h1i"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
ne240x2_QxQsst:
  name: "c153_topfix_ne240pg3_FMTHIST_QxQsst_xic_x02"
  user: "juliob"
  subdir: "hist"
  SrcGrid: "ne240pg3"
  Hkey: "c"
  DstGrid: "latlonOxO"
  hsPat: "cam.h1i"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
ne240x2_QxQsst_smth:
  name: "c153_topfix_ne240pg3_FMTHIST_QxQsst_smth_xic_x02"
  user: "juliob"
  subdir: "hist"
  SrcGrid: "ne240pg3"
  Hkey: "c"
  DstGrid: "latlonOxO"
  hsPat: "cam.h1i"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
c153_ne30_x2:
  name: "c153_ne30pg3_FMTHIST_x02"
  user: "juliob_camp"
  subdir: "hist"
  SrcGrid: "ne30pg3"
  Hkey: "c"
  DstGrid: "fv1x1"
  hsPat: "cam.h1i"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
c153_ne30_x5:
  name: "c153_ne30pg3_FMTHIST_x05"
  user: "juliob"
  subdir: "hist"
  SrcGrid: "ne30pg3"
  Hkey: "c"
  DstGrid: "fv1x1"
  hsPat: "cam.h1i"
  ymdPat: "2004-*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
c153_ne120_x2:
  name: "c153_topfix_ne120pg3_FMTHIST_xic_x02"
  user: "juliob"
  subdir: "hist"
  SrcGrid: "ne120pg3"
  Hkey: "c"
  DstGrid: "fv1x1"
  hsPat: "cam.h1i"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
oldCTL:
  name: "c64_gwR2_ne30pg3_FMTHIST_topfix_oldCTL_qbotune_x03"
  user: "juliob"
  subdir: "hist"
  SrcGrid: "ne30pg3"
  Hkey: "c"
  DstGrid: "fv1x1"
  hsPat: "cam.h0a"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
newCTL:
  name: "c64_gwR2_ne30pg3_FMTHIST_topfix_x02"
  user: "juliob"
  subdir: "hist"
  SrcGrid: "ne30pg3"
  Hkey: "c"
  DstGrid: "fv1x1"
  hsPat: "cam.h0a"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
c64_rdgres:
  name: "c64_gwR2_ne30pg3_FMTHIST_topfix_rdgres_x02"
  user: "juliob"
  subdir: "hist"
  SrcGrid: "ne30pg3"
  Hkey: "c"
  DstGrid: "fv1x1"
  hsPat: "cam.h0a"
  ymdPat: [ "*-06-*-*","*-07-*-*","*-08-*-*",]  #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
waccmL135:
  name: "FWscHIST_ne30pg3_cam7phys_t01_L135start1985"
  user: "bramberg"
  subdir: "hist"
  SrcGrid: "ne30pg3"
  Hkey: "c"
  DstGrid: "fv1x1"
  hsPat: "cam.h0a"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
##############################
# Some runs Cecile has done
##############################
cam6_3_160_L93_x01:
  name: "f.cam6_3_160.FMTHIST_ne30.001"
  user: "hannay"
  subdir: "hist"
  SrcGrid: "fv1x1"
  Hkey: "yx"
  DstGrid: "fv1x1"
  hsPat: "cam.h0a"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
cam6_4_036_L93_x02:
  name: "f.e30_cam6_4_036.FMTHIST.ne30_L93.002"
  user: "hannay"
  subdir: "hist"
  SrcGrid: "fv1x1"
  Hkey: "yx"
  DstGrid: "fv1x1"
  hsPat: "cam.h0a"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
alpha04aL93ctl:
  name: "f.e30_alpha04a.FMTHIST.ne30_L93.004"
  user: "hannay"
  subdir: "hist"
  SrcGrid: "fv1x1"
  Hkey: "yx"
  DstGrid: "fv1x1"
  hsPat: "cam.h0a"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
SpongeFix:
  name: "f.e30_alpha04a.FMTHIST.ne30_L93.sponge_fix.005"
  user: "hannay"
  subdir: "hist"
  SrcGrid: "fv1x1"
  Hkey: "yx"
  DstGrid: "fv1x1"
  hsPat: "cam.h0a"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
alpha04ax010:
  name: "f.e30_alpha04a.FMTHIST.ne30_L93_tuning.010"
  user: "hannay"
  subdir: "hist"
  SrcGrid: "fv1x1"
  Hkey: "yx"
  DstGrid: "fv1x1"
  hsPat: "cam.h0a"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
alpha04ax009:
  name: "f.e30_alpha04a.FMTHIST.ne30_L93_tuning.009"
  user: "hannay"
  subdir: "hist"
  SrcGrid: "fv1x1"
  Hkey: "yx"
  DstGrid: "fv1x1"
  hsPat: "cam.h0a"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
alpha04ax008:
  name: "f.e30_alpha04a.FMTHIST.ne30_L93_tuning.008"
  user: "hannay"
  subdir: "hist"
  SrcGrid: "fv1x1"
  Hkey: "yx"
  DstGrid: "fv1x1"
  hsPat: "cam.h0a"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2
alpha04ax007:
  name: "f.e30_alpha04a.FMTHIST.ne30_L93_tuning.007"
  user: "hannay"
  subdir: "hist"
  SrcGrid: "fv1x1"
  Hkey: "yx"
  DstGrid: "fv1x1"
  hsPat: "cam.h0a"
  ymdPat: "*" #["1985-*","1986-*"]
  parameters:
    param1: 1
    param2: 2

