A:
  name: "c153_ne30pg3_FMTHIST_x01"
  user: "juliob"
  grid: "hist"
  hsPat: "cam.h0a"
  ymdPat: "*"
  parameters:
    param1: 1
    param2: 2
B:
  name: "c153_ne30pg3_FMTHIST_x02"
  user: "juliob"
  grid: "regridded"
  hsPat: "cam.h0a"
  ymdPat: "*"
  parameters:
    param1: 1
    param2: 2
plot:
    field: 'PS'
    season: 'ann'
